-- COREQ_BOX.CODE_MODULE definition

CREATE TABLE "COREQ_BOX"."CODE_MODULE" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(100), 
	"AUTO" CHAR(1) DEFAULT '0', 
	"INS" CHAR(1) DEFAULT 0, 
	 CONSTRAINT "PK_CODE_MODULE" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_CODE_MODULE" ON "COREQ_BOX"."CODE_MODULE" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.CODE_MODULE IS '시스템 모듈 정보 (CDM)';
COMMENT ON COLUMN COREQ_BOX.CODE_MODULE.CID IS '일련번호 (CDM)';
COMMENT ON COLUMN COREQ_BOX.CODE_MODULE.NAME IS '모듈 영문명';
COMMENT ON COLUMN COREQ_BOX.CODE_MODULE."TYPE" IS '모듈 한글명';
COMMENT ON COLUMN COREQ_BOX.CODE_MODULE.DESCRIPTION IS '비고';
COMMENT ON COLUMN COREQ_BOX.CODE_MODULE.AUTO IS '자동채번여부';
COMMENT ON COLUMN COREQ_BOX.CODE_MODULE.INS IS '설치여부';


-- COREQ_BOX.COMPANY definition

CREATE TABLE "COREQ_BOX"."COMPANY" 
   (	"CID" VARCHAR2(10) NOT NULL ENABLE, 
	"NO" VARCHAR2(20) NOT NULL ENABLE, 
	"NAME" VARCHAR2(35) NOT NULL ENABLE, 
	"MANUFACTURE" CHAR(1) DEFAULT 0, 
	"PURCHASE" CHAR(1) DEFAULT 0, 
	"CLIENT" CHAR(1) DEFAULT 0, 
	"LOCKED" CHAR(1) DEFAULT 0, 
	"DESCRIPTION" VARCHAR2(250), 
	"CREATEDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ENABLED" CHAR(1) DEFAULT 1, 
	"OWNER" VARCHAR2(20 CHAR), 
	"CREATOR" VARCHAR2(20 CHAR), 
	 CONSTRAINT "PK_COMPANY" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_COMPANY" ON "COREQ_BOX"."COMPANY" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.COMPANY IS '회사';
COMMENT ON COLUMN COREQ_BOX.COMPANY.CID IS '회사 : COM';
COMMENT ON COLUMN COREQ_BOX.COMPANY.MANUFACTURE IS '공급 여부';
COMMENT ON COLUMN COREQ_BOX.COMPANY.PURCHASE IS '구매 여부';
COMMENT ON COLUMN COREQ_BOX.COMPANY.CLIENT IS '고객사';
COMMENT ON COLUMN COREQ_BOX.COMPANY.DESCRIPTION IS '비고';
COMMENT ON COLUMN COREQ_BOX.COMPANY.ENABLED IS '사용여부';
COMMENT ON COLUMN COREQ_BOX.COMPANY.OWNER IS '생성자 또는 관리자';


-- COREQ_BOX.MODEL_IMAGE_FILE definition

CREATE TABLE "COREQ_BOX"."MODEL_IMAGE_FILE" 
   (	"CID" VARCHAR2(100) NOT NULL ENABLE, 
	"REFCID" VARCHAR2(20), 
	"SEQ" NUMBER DEFAULT 1, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(100), 
	"FILESIZE" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(256), 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "PK_MODEL_IMAGE_FILE" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_MODEL_IMAGE_FILE" ON "COREQ_BOX"."MODEL_IMAGE_FILE" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.MODEL_IMAGE_FILE IS 'DWG TO IMG 변환파일';
COMMENT ON COLUMN COREQ_BOX.MODEL_IMAGE_FILE.CID IS '일련번호, UUID로 Storage 저장시 사용';
COMMENT ON COLUMN COREQ_BOX.MODEL_IMAGE_FILE.REFCID IS '관련 오브젝트 CID';
COMMENT ON COLUMN COREQ_BOX.MODEL_IMAGE_FILE.SEQ IS '순번';
COMMENT ON COLUMN COREQ_BOX.MODEL_IMAGE_FILE.NAME IS '파일명';
COMMENT ON COLUMN COREQ_BOX.MODEL_IMAGE_FILE.TITLE IS '이름';
COMMENT ON COLUMN COREQ_BOX.MODEL_IMAGE_FILE.DESCRIPTION IS '비고';
COMMENT ON COLUMN COREQ_BOX.MODEL_IMAGE_FILE.CREATEDATE IS '생성일';


-- COREQ_BOX.PART_CATEGORY_RELATION definition

CREATE TABLE "COREQ_BOX"."PART_CATEGORY_RELATION" 
   (	"TYPCID" VARCHAR2(20) NOT NULL ENABLE, 
	"ICTCID" VARCHAR2(20) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

COMMENT ON COLUMN COREQ_BOX.PART_CATEGORY_RELATION.TYPCID IS '파트 구분 CID (TYP)';
COMMENT ON COLUMN COREQ_BOX.PART_CATEGORY_RELATION.ICTCID IS '분류체계 CID (ICT)';


-- COREQ_BOX.PART_MODEL_RELATION definition

CREATE TABLE "COREQ_BOX"."PART_MODEL_RELATION" 
   (	"PARTID" VARCHAR2(20) NOT NULL ENABLE, 
	"MODELID" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "PK_PART_MODEL_REL" PRIMARY KEY ("PARTID", "MODELID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_PART_MODEL_REL" ON "COREQ_BOX"."PART_MODEL_RELATION" ("PARTID", "MODELID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.PART_MODEL_RELATION IS '파트 모델 연결 정보';
COMMENT ON COLUMN COREQ_BOX.PART_MODEL_RELATION.PARTID IS '파트 버전 CID';
COMMENT ON COLUMN COREQ_BOX.PART_MODEL_RELATION.MODELID IS '모델 CID';


-- COREQ_BOX.PROJECT_COST definition

CREATE TABLE "COREQ_BOX"."PROJECT_COST" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"PROJECTCID" VARCHAR2(20), 
	"ITEM" VARCHAR2(256), 
	"GOAL" NUMBER(20,2), 
	"PERFORMANCE" NUMBER(20,2), 
	"DESCRIPTION" VARCHAR2(2000), 
	 CONSTRAINT "PK_CID" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_CID" ON "COREQ_BOX"."PROJECT_COST" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

COMMENT ON COLUMN COREQ_BOX.PROJECT_COST.CID IS '투자비 ID';
COMMENT ON COLUMN COREQ_BOX.PROJECT_COST.PROJECTCID IS 'Project ID';
COMMENT ON COLUMN COREQ_BOX.PROJECT_COST.ITEM IS '항목';
COMMENT ON COLUMN COREQ_BOX.PROJECT_COST.GOAL IS '목표';
COMMENT ON COLUMN COREQ_BOX.PROJECT_COST.PERFORMANCE IS '실적';
COMMENT ON COLUMN COREQ_BOX.PROJECT_COST.DESCRIPTION IS '비고';


-- COREQ_BOX.USER_ACCESS definition

CREATE TABLE "COREQ_BOX"."USER_ACCESS" 
   (	"CID" VARCHAR2(10), 
	"IP" VARCHAR2(30), 
	"CONNECTDATE" DATE, 
	"CLOSEDATE" DATE, 
	"USERCID" VARCHAR2(10), 
	 CONSTRAINT "PK_USERACCESS" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_USERACCESS" ON "COREQ_BOX"."USER_ACCESS" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.USER_ACCESS IS '사용자 접속 정보';
COMMENT ON COLUMN COREQ_BOX.USER_ACCESS.CID IS '일련번호 : USA';
COMMENT ON COLUMN COREQ_BOX.USER_ACCESS.IP IS '접속 IP';
COMMENT ON COLUMN COREQ_BOX.USER_ACCESS.CONNECTDATE IS '로그인 시간';
COMMENT ON COLUMN COREQ_BOX.USER_ACCESS.CLOSEDATE IS '로그아웃 시간';
COMMENT ON COLUMN COREQ_BOX.USER_ACCESS.USERCID IS '사용자 일련번호';


-- COREQ_BOX.CODE_TYPE definition

CREATE TABLE "COREQ_BOX"."CODE_TYPE" 
   (	"CID" VARCHAR2(10) NOT NULL ENABLE, 
	"NAME" VARCHAR2(3) NOT NULL ENABLE, 
	"MODULECID" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(256), 
	"LOCKED" CHAR(1) DEFAULT 0, 
	"AUTO" CHAR(1) DEFAULT 0, 
	"SYSCODE" CHAR(1), 
	 CONSTRAINT "PK_CODE_TYPE" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

ALTER TABLE "COREQ_BOX"."CODE_TYPE" ADD CONSTRAINT "FK_MODULE_TYPE" FOREIGN KEY ("MODULECID")
	  REFERENCES "COREQ_BOX"."CODE_MODULE" ("CID") ON DELETE CASCADE ENABLE;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_CODE_TYPE" ON "COREQ_BOX"."CODE_TYPE" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.CODE_TYPE IS '코드 타입 정보 (CDT)';
COMMENT ON COLUMN COREQ_BOX.CODE_TYPE.CID IS '일련번호 : CDT';
COMMENT ON COLUMN COREQ_BOX.CODE_TYPE.NAME IS '모듈 영문명';
COMMENT ON COLUMN COREQ_BOX.CODE_TYPE.MODULECID IS '시스템 모듈 일련번호';
COMMENT ON COLUMN COREQ_BOX.CODE_TYPE.DESCRIPTION IS '비고';
COMMENT ON COLUMN COREQ_BOX.CODE_TYPE.LOCKED IS '시스템 코드 여부';
COMMENT ON COLUMN COREQ_BOX.CODE_TYPE.AUTO IS '자동채번여부';
COMMENT ON COLUMN COREQ_BOX.CODE_TYPE.SYSCODE IS '코드 타입(코드마스터성)에 시스템코드 여부를 추가한다. 시스템코드는 수정불가.';


-- COREQ_BOX.BOM definition

CREATE TABLE "COREQ_BOX"."BOM" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"PARENT" VARCHAR2(20) NOT NULL ENABLE, 
	"CHILD" VARCHAR2(20) NOT NULL ENABLE, 
	"STARTPARENT" VARCHAR2(20) NOT NULL ENABLE, 
	"STARTCHILD" VARCHAR2(20) NOT NULL ENABLE, 
	"ENDCHILD" VARCHAR2(20), 
	"ENDPARENT" VARCHAR2(20), 
	"SEQ" VARCHAR2(10) NOT NULL ENABLE, 
	"QTY" NUMBER(16,5) DEFAULT 1 NOT NULL ENABLE, 
	"APPROVEDATE" DATE, 
	"STARTDATE" DATE, 
	"ENDDATE" DATE, 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	"LOCATION" VARCHAR2(256 CHAR), 
	 CONSTRAINT "PK_BOM" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_BOM" ON "COREQ_BOX"."BOM" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.BOM IS 'BOM 정보';
COMMENT ON COLUMN COREQ_BOX.BOM.CID IS '일련번호 : BOM';
COMMENT ON COLUMN COREQ_BOX.BOM.PARENT IS 'BOM의 상위 부품의 마스터 CID';
COMMENT ON COLUMN COREQ_BOX.BOM.CHILD IS 'BOM의 하위 부품의 마스터 CID';
COMMENT ON COLUMN COREQ_BOX.BOM.STARTPARENT IS '현재 BOM의 사용이 시작된 시점의 PARENT 부품의 REVISION정보';
COMMENT ON COLUMN COREQ_BOX.BOM.STARTCHILD IS '현재 BOM의 사용이 시작된 시점의 하위 부품의 REVISION정보';
COMMENT ON COLUMN COREQ_BOX.BOM.ENDCHILD IS '현재 BOM의 사용이 종료된 시점의 하위 부품의 REVISION정보';
COMMENT ON COLUMN COREQ_BOX.BOM.ENDPARENT IS '현재 BOM연결이 종료된 시점의 PARENT 부품의 REVISION정보 1. 상위가 리비전 되어 수정되어지는 경우에 입력됨- 기존 BOM정보에는 ENDPARENT, 신규 BOM정보에는 STARTPARENT에 현재 상위부품의 REVISION 값이 입력됨 2. 하위가 리비전 되어지는 경우에 입력됨';
COMMENT ON COLUMN COREQ_BOX.BOM.SEQ IS 'BOM의 수량을 입력하는 컬럼';
COMMENT ON COLUMN COREQ_BOX.BOM.QTY IS '수량정보를 입력하는 컬럼';
COMMENT ON COLUMN COREQ_BOX.BOM.APPROVEDATE IS 'ECO에 의해서 상위 부품의 REVISION이 승인된 날짜가 입력된다.';
COMMENT ON COLUMN COREQ_BOX.BOM.STARTDATE IS '상위 부품과 하위 부품이 연결되거나 수정된후 상위와 하위의 연결이 ECO에 의해 확정된 날짜';
COMMENT ON COLUMN COREQ_BOX.BOM.ENDDATE IS '현재 BOM연결이 종료된 날짜 또는 종료 될 날짜 1. 최초연결시에는 2049년 12월 31일로 입력됨 2. 상위가 리비전된후에 해당 연결이 수정된후 확정된 날짜 - 신규로 BOM정보가 추가되어지고 추가된 BOM정보의 STARTDATE와 이전 BOM정보의 ENDDATE와 같다 3. 하위가 리비전 되고 확정된 날짜 4. 하위가 삭제되고 상위가 확정되는 날짜';
COMMENT ON COLUMN COREQ_BOX.BOM.CREATEDATE IS '현재로우가 추가된 날자를 관리하기위해 데이터 확인 및 수정 보정을 위해서';


-- COREQ_BOX.CODE definition

CREATE TABLE "COREQ_BOX"."CODE" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"TYPECID" VARCHAR2(20) NOT NULL ENABLE, 
	"SEQ" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100), 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	"FORMAT" VARCHAR2(200), 
	"ENABLED" CHAR(1) DEFAULT '1', 
	"CODE" VARCHAR2(10), 
	"AUTO" CHAR(1) DEFAULT '0', 
	"KEEP" VARCHAR2(2), 
	"COUNT" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"ROOTCODE" CHAR(1) DEFAULT '0', 
	"LOCKED" CHAR(1), 
	 CONSTRAINT "PK_CODE" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE INDEX "COREQ_BOX"."CODE_INDEX1" ON "COREQ_BOX"."CODE" ("CID", "TYPECID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;
  CREATE UNIQUE INDEX "COREQ_BOX"."PK_CODE" ON "COREQ_BOX"."CODE" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.CODE IS '코드 정보';
COMMENT ON COLUMN COREQ_BOX.CODE.CID IS '일련번호 : CODE_TYPE의 NAME 기준으로 prefix가 정해짐';
COMMENT ON COLUMN COREQ_BOX.CODE.NAME IS '이름';
COMMENT ON COLUMN COREQ_BOX.CODE.TYPECID IS '코드 타입  일련번호';
COMMENT ON COLUMN COREQ_BOX.CODE.SEQ IS '순번';
COMMENT ON COLUMN COREQ_BOX.CODE.DESCRIPTION IS '비고';
COMMENT ON COLUMN COREQ_BOX.CODE.CREATEDATE IS '등록일';
COMMENT ON COLUMN COREQ_BOX.CODE.FORMAT IS '문서 분류 체계별 Format CID';
COMMENT ON COLUMN COREQ_BOX.CODE.ENABLED IS '사용 여부';
COMMENT ON COLUMN COREQ_BOX.CODE.CODE IS '파트 분류 체계 코드';
COMMENT ON COLUMN COREQ_BOX.CODE.AUTO IS '자동채번여부';
COMMENT ON COLUMN COREQ_BOX.CODE.KEEP IS '문서 분류 체계별 보존년한';
COMMENT ON COLUMN COREQ_BOX.CODE.COUNT IS '등록 현황';
COMMENT ON COLUMN COREQ_BOX.CODE.ROOTCODE IS '분류체계의 최상위 코드인지 구분하기 위한 컬럼.';
COMMENT ON COLUMN COREQ_BOX.CODE.LOCKED IS '코드별 시스템 코드 여부';


-- COREQ_BOX.CODE_CATEGORY definition

CREATE TABLE "COREQ_BOX"."CODE_CATEGORY" 
   (	"PARENTCODE" VARCHAR2(20) NOT NULL ENABLE, 
	"CHILDCODE" VARCHAR2(20) NOT NULL ENABLE, 
	"SEQ" NUMBER NOT NULL ENABLE, 
	"GROUPCODE" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(100), 
	 CONSTRAINT "CODE_CATEGORY_PK" PRIMARY KEY ("PARENTCODE", "CHILDCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."CODE_CATEGORY_PK" ON "COREQ_BOX"."CODE_CATEGORY" ("PARENTCODE", "CHILDCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.CODE_CATEGORY IS '코드 카테고리 정보';
COMMENT ON COLUMN COREQ_BOX.CODE_CATEGORY.PARENTCODE IS 'PARENT 코드';
COMMENT ON COLUMN COREQ_BOX.CODE_CATEGORY.CHILDCODE IS 'CHILD 코드';


-- COREQ_BOX.MODEL_DETAIL definition

CREATE TABLE "COREQ_BOX"."MODEL_DETAIL" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"MASTERCID" VARCHAR2(20) NOT NULL ENABLE, 
	"ORIGINATOR" VARCHAR2(20) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(20) NOT NULL ENABLE, 
	"MODELSRC" VARCHAR2(20), 
	"CUSTOMERECO" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(100), 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	"CHANGEDATE" DATE, 
	"APPROVEDATE" DATE, 
	"APPROVALCOMMENT" VARCHAR2(100), 
	"WORKFLOW" VARCHAR2(30), 
	"ECOCID" VARCHAR2(20 CHAR), 
	"MODELREASON" VARCHAR2(10 CHAR), 
	 CONSTRAINT "PK_MODEL_DETAIL" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_MODEL_DETAIL" ON "COREQ_BOX"."MODEL_DETAIL" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.MODEL_DETAIL IS '도면 상세 정보';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.CID IS '일련번호 : MOD';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.MASTERCID IS '마스터 일련번호(PK)';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.ORIGINATOR IS '작성자(FK)';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.STATUS IS '상태(FK)';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.VERSION IS '버젼';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.MODELSRC IS '출처(FK)';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.CUSTOMERECO IS '업체eco';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.DESCRIPTION IS '비고';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.CREATEDATE IS '생성일';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.CHANGEDATE IS '수정일';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL.APPROVEDATE IS '승인일';


-- COREQ_BOX.MODEL_DETAIL_FILE definition

CREATE TABLE "COREQ_BOX"."MODEL_DETAIL_FILE" 
   (	"CID" VARCHAR2(20), 
	"DETAILCID" VARCHAR2(20) NOT NULL ENABLE, 
	"SEQ" NUMBER NOT NULL ENABLE, 
	"CLASSIFICATION" VARCHAR2(20) NOT NULL ENABLE, 
	"SOFTWARE" VARCHAR2(20), 
	"TYPE" VARCHAR2(20), 
	"MODELSIZE" VARCHAR2(20), 
	"ORIGINALNAME" VARCHAR2(500) NOT NULL ENABLE, 
	"SAVENAME" VARCHAR2(500) NOT NULL ENABLE, 
	"SAVEPATH" VARCHAR2(500) NOT NULL ENABLE, 
	"CHECKOUTDATE" DATE, 
	"CHECKINDATE" DATE, 
	"CHECKOUTUSER" VARCHAR2(20), 
	"CHECKOUTREASON" VARCHAR2(1000), 
	"CHECKOUT" CHAR(1) DEFAULT 0, 
	"IS2D" CHAR(1) DEFAULT 1, 
	"FILESIZE" NUMBER(10,0) DEFAULT 0, 
	 CONSTRAINT "PK_MODEL_DETAIL_FILE" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_MODEL_DETAIL_FILE" ON "COREQ_BOX"."MODEL_DETAIL_FILE" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.MODEL_DETAIL_FILE IS '도면 파일';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.CID IS '일련번호 : MDF';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.DETAILCID IS '상세정보 일련번호(FK)';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.SEQ IS '파일의 인덱스';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.CLASSIFICATION IS '분류(예:승인도, 시작도...)(FK_CODE) ';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.SOFTWARE IS '파일 종류(예:CAD, AUTOCAT, CATIA_V5...)(FK_SOFTWARE) ';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE."TYPE" IS '파일 구분(예:2D, 3D..)(FK) ';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.MODELSIZE IS '도면 크기 (예:A1, A2, A0...)(FK_CODE) ';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.ORIGINALNAME IS '순수 파일명';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.SAVENAME IS '저장된 실제 파일명';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.SAVEPATH IS '저장된 경로';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.IS2D IS '2D 여부';
COMMENT ON COLUMN COREQ_BOX.MODEL_DETAIL_FILE.FILESIZE IS '파일 사이즈';


-- COREQ_BOX.MODEL_FILE_RELATION definition

CREATE TABLE "COREQ_BOX"."MODEL_FILE_RELATION" 
   (	"MODELID" VARCHAR2(20) NOT NULL ENABLE, 
	"FILEID" VARCHAR2(50) NOT NULL ENABLE, 
	 CONSTRAINT "PK_MODEL_FILE_REL" PRIMARY KEY ("MODELID", "FILEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_MODEL_FILE_REL" ON "COREQ_BOX"."MODEL_FILE_RELATION" ("MODELID", "FILEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.MODEL_FILE_RELATION IS '관련 도면 테이블';
COMMENT ON COLUMN COREQ_BOX.MODEL_FILE_RELATION.MODELID IS '도면 상세정보 일련번호';
COMMENT ON COLUMN COREQ_BOX.MODEL_FILE_RELATION.FILEID IS '도면 파일 일련번호';


-- COREQ_BOX.MODEL_MASTER definition

CREATE TABLE "COREQ_BOX"."MODEL_MASTER" 
   (	"CID" VARCHAR2(20), 
	"NO" VARCHAR2(50) NOT NULL ENABLE, 
	"PARTCID" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_MODEL_MASTER" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_MODEL_MASTER" ON "COREQ_BOX"."MODEL_MASTER" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.MODEL_MASTER IS '도면 마스터';
COMMENT ON COLUMN COREQ_BOX.MODEL_MASTER.CID IS '일련번호 : MOM';
COMMENT ON COLUMN COREQ_BOX.MODEL_MASTER."NO" IS '번호 : 부품번호를 검색해서 등록함';
COMMENT ON COLUMN COREQ_BOX.MODEL_MASTER.PARTCID IS '파트 디테일 일련번호(FK)';
COMMENT ON COLUMN COREQ_BOX.MODEL_MASTER.STATUS IS '최종 상태';


-- COREQ_BOX.PART_DETAIL definition

CREATE TABLE "COREQ_BOX"."PART_DETAIL" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"MASTERCID" VARCHAR2(20) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(20) NOT NULL ENABLE, 
	"PARTSUBNAME" VARCHAR2(50), 
	"SPEC" VARCHAR2(100), 
	"SURFACE" VARCHAR2(20), 
	"COST" NUMBER(20,0), 
	"PROJECT" VARCHAR2(30), 
	"COLOR" VARCHAR2(20), 
	"WEIGHT" NUMBER(16,5), 
	"MATTER" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(1000), 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	"CHANGEDATE" DATE, 
	"APPROVEDATE" DATE, 
	"STATUS" VARCHAR2(20), 
	"ORIGINATOR" VARCHAR2(20) NOT NULL ENABLE, 
	"SHARED_PART" CHAR(1), 
	"ASSEMBLY_PART" CHAR(1) DEFAULT '1', 
	"ISPRODUCT" CHAR(1), 
	"ESTIMATE_WEIGHT" NUMBER(16,5), 
	"WEIGHT_UOM" VARCHAR2(10), 
	"APPLY_MODEL" VARCHAR2(250), 
	"AS_PART" CHAR(1), 
	"SUPPLY_TYPE" VARCHAR2(10), 
	"MFG_COMPANY" VARCHAR2(40), 
	"MODELNAME" VARCHAR2(100), 
	"RAW_CID" VARCHAR2(20), 
	"RAW_SPEC" VARCHAR2(100), 
	"RAW_NAME" VARCHAR2(100), 
	"RAW_LENGTH" NUMBER(16,5), 
	"RAW_SPEC2" VARCHAR2(100), 
	"RAW_SPEC3" VARCHAR2(100), 
	"RAW_WIDTH" NUMBER(16,5), 
	"RAW_HEIGHT" NUMBER(16,5), 
	"RAW_WEIGHT" NUMBER(16,5), 
	"POWDER_CID" VARCHAR2(20), 
	"POWDER_QTY" NUMBER(10,2), 
	"DISUSED_PART" CHAR(1), 
	"PROCESS_CONTROL_PART" CHAR(1), 
	"SUPPLY_COMPANY" VARCHAR2(40), 
	"PROJECTNAME" VARCHAR2(100), 
	"BUYER" VARCHAR2(100), 
	"TRUSTINFO" VARCHAR2(100), 
	"ISSAFEPART" VARCHAR2(20), 
	"SELLINGAGENCY" VARCHAR2(20), 
	"ISMOLD" VARCHAR2(20), 
	"NOTE" CLOB, 
	"TEMP_EST_COST" NUMBER(20,0), 
	 CONSTRAINT "PK_PART_DETAIL" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" 
 LOB ("NOTE") STORE AS SECUREFILE (
  TABLESPACE "COREQ_BOX_TBS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "COREQ_BOX"."SYS_IL0000350714C00048$$" ON "COREQ_BOX"."PART_DETAIL" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "COREQ_BOX"."PK_PART_DETAIL" ON "COREQ_BOX"."PART_DETAIL" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.PART_DETAIL IS '파트 버전 정보';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.CID IS '일련번호 : PRD';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.SHARED_PART IS '공용 부품';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.ASSEMBLY_PART IS 'Assy 부품';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.ISPRODUCT IS '제품구분';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.ESTIMATE_WEIGHT IS '예상 중량';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.WEIGHT_UOM IS '중량단위[UOW]';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.APPLY_MODEL IS '적용 모델';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.AS_PART IS 'AS 모델';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.SUPPLY_TYPE IS '공급(조달)구분';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.MFG_COMPANY IS '제조업체';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.MODELNAME IS '모델명';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_CID IS '원재료번호';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_SPEC IS '원재료규격';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_NAME IS '원재료명';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_LENGTH IS '원재료길이';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_SPEC2 IS '원재료규격2(사용중지)';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_SPEC3 IS '원재료규격3(사용중지)';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_WIDTH IS '원재료가로';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_HEIGHT IS '원재료세로';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.RAW_WEIGHT IS '원재료중량';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.POWDER_CID IS '파우더/기타';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.POWDER_QTY IS '파우더소요량';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.SUPPLY_COMPANY IS '납품업체';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.PROJECTNAME IS '프로젝트명';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.BUYER IS 'BUYER';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.TRUSTINFO IS '인증정보';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.ISSAFEPART IS '안전부품여부';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.SELLINGAGENCY IS '판매처';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.ISMOLD IS '금형여부';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.NOTE IS '비고를 Summer Note Editor Format(HTML)으로 저장';
COMMENT ON COLUMN COREQ_BOX.PART_DETAIL.TEMP_EST_COST IS '가설계원가 (Dashboard)';


-- COREQ_BOX.PART_MASTER definition

CREATE TABLE "COREQ_BOX"."PART_MASTER" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"NO" VARCHAR2(20) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(20) NOT NULL ENABLE, 
	"CLASSIFICATION" VARCHAR2(20) NOT NULL ENABLE, 
	"PRODUCTLINE" VARCHAR2(20), 
	"OLDNO" VARCHAR2(20), 
	"UOM" VARCHAR2(20) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20), 
	"MANUFACTURINGINFO" VARCHAR2(10), 
	"CUSTOMERNO" VARCHAR2(30), 
	"CUSTOMERNAME" VARCHAR2(50), 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	"APPROVEDATE" DATE, 
	"LASTVERSIONCID" VARCHAR2(20), 
	"LASTRELEASECID" VARCHAR2(20), 
	 CONSTRAINT "UK_NO_PARTMASTER" UNIQUE ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS"  ENABLE, 
	 CONSTRAINT "PK_PART_MASTER" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."UK_NO_PARTMASTER" ON "COREQ_BOX"."PART_MASTER" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;
  CREATE UNIQUE INDEX "COREQ_BOX"."PK_PART_MASTER" ON "COREQ_BOX"."PART_MASTER" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.PART_MASTER IS '파트 버전 정보';
COMMENT ON COLUMN COREQ_BOX.PART_MASTER.CID IS '일련번호 : PRM';


-- COREQ_BOX.PART_OBJECT_RELATION definition

CREATE TABLE "COREQ_BOX"."PART_OBJECT_RELATION" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"PARTID" VARCHAR2(20), 
	"OBJECTID" VARCHAR2(20), 
	"TYPE" VARCHAR2(20), 
	"SUPPLYTYPE" VARCHAR2(20), 
	"COST" NUMBER(20,0), 
	"DESCRIPTION" VARCHAR2(100), 
	"CLIENTCOMPAY" VARCHAR2(10), 
	"CLIENT" VARCHAR2(10), 
	"RAWDIM" VARCHAR2(128), 
	"RAWDIM1" VARCHAR2(128), 
	"RAWDIM2" VARCHAR2(128), 
	"QTY" NUMBER(20,0), 
	"COSTUNIT" VARCHAR2(20), 
	 CONSTRAINT "PK_PART_OBJECT_REL" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_PART_OBJECT_REL" ON "COREQ_BOX"."PART_OBJECT_RELATION" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.PART_OBJECT_RELATION IS '파트 원재료/재조/고객사  연결 정보';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.CID IS '일련번호 : POR';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.DESCRIPTION IS '거래내역';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.CLIENTCOMPAY IS '고객사';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.CLIENT IS '고객 담당자';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.RAWDIM IS '원재료 규격';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.RAWDIM1 IS '원재료 규격1/가로';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.RAWDIM2 IS '원재료 규격2/세로';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.QTY IS '파우더소요량';
COMMENT ON COLUMN COREQ_BOX.PART_OBJECT_RELATION.COSTUNIT IS '화폐단위';


-- COREQ_BOX.PROJECT definition

CREATE TABLE "COREQ_BOX"."PROJECT" 
   (	"CID" VARCHAR2(10) NOT NULL ENABLE, 
	"NO" VARCHAR2(20) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"PRODUCTLINE" VARCHAR2(10), 
	"MANAGER" VARCHAR2(10), 
	"TEAM" VARCHAR2(10), 
	"CREATEDATE" DATE, 
	"ORIGINATOR" VARCHAR2(10), 
	"TYPE" VARCHAR2(10), 
	"GRADE" VARCHAR2(10), 
	"TYPICALPART" VARCHAR2(10), 
	"YEARQTY" NUMBER(20,2), 
	"TARGETDATE" DATE, 
	"PLANCOST" NUMBER(20,2), 
	"TOTALCOST" NUMBER(20,2), 
	"DESCRIPTION" VARCHAR2(1000), 
	"CLIENTCOMPANY" VARCHAR2(10), 
	"CLIENT" VARCHAR2(10), 
	"CLIENTPHONE" VARCHAR2(20), 
	"CLIENTPLANDATE" DATE, 
	"CLIENTPARTNO" VARCHAR2(30), 
	"CLIENTPARTNAME" VARCHAR2(50), 
	"CLIENTDESCRIPTION" VARCHAR2(1000), 
	"STATUS" VARCHAR2(10), 
	"REFPROJECTCID" VARCHAR2(10), 
	"STARTDATE" DATE, 
	"FINISHDATE" DATE, 
	"WORKFLOW" VARCHAR2(20), 
	"COMMENTS" VARCHAR2(1000), 
	"APPROVEDATE" DATE, 
	"STARTPLANDATE" DATE, 
	"FINISHPLANDATE" DATE, 
	"PROGRESSRATE" NUMBER(20,2), 
	"DURATION" NUMBER DEFAULT 1, 
	"SALESAREA" VARCHAR2(10), 
	"WORKSAMPLE" NUMBER(20,0) DEFAULT 0, 
	"ENGINEERSAMPLE" NUMBER(20,0) DEFAULT 0, 
	"PILOT" NUMBER(20,0) DEFAULT 0, 
	"PREPRODUCTION" NUMBER(20,0) DEFAULT 0, 
	"LEV" VARCHAR2(10), 
	"CLASSIFICATION" VARCHAR2(10), 
	"MODELNAME" VARCHAR2(50), 
	"TEMPLATENO" VARCHAR2(20), 
	"CLIENT_FILE" VARCHAR2(20), 
	"STATUSANALYSIS" VARCHAR2(1000), 
	"COMPETITIVESTRATEGY" VARCHAR2(1000), 
	"DEVELOPMENTSPECIFICATION" VARCHAR2(1000), 
	 CONSTRAINT "PK_PROJECT" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_PROJECT" ON "COREQ_BOX"."PROJECT" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.PROJECT IS '프로젝트';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CID IS '일련번호';
COMMENT ON COLUMN COREQ_BOX.PROJECT."NO" IS '번호';
COMMENT ON COLUMN COREQ_BOX.PROJECT.NAME IS '이름';
COMMENT ON COLUMN COREQ_BOX.PROJECT.PRODUCTLINE IS '모델';
COMMENT ON COLUMN COREQ_BOX.PROJECT.MANAGER IS '관리자';
COMMENT ON COLUMN COREQ_BOX.PROJECT.TEAM IS '책임부서';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CREATEDATE IS '등록일';
COMMENT ON COLUMN COREQ_BOX.PROJECT.ORIGINATOR IS '등록자';
COMMENT ON COLUMN COREQ_BOX.PROJECT."TYPE" IS '구분(자체/OEM/일반)';
COMMENT ON COLUMN COREQ_BOX.PROJECT.GRADE IS '개발등급(1,2,3,4 등급)';
COMMENT ON COLUMN COREQ_BOX.PROJECT.TYPICALPART IS '부품';
COMMENT ON COLUMN COREQ_BOX.PROJECT.YEARQTY IS '연간생산수량';
COMMENT ON COLUMN COREQ_BOX.PROJECT.TARGETDATE IS '최종목표일';
COMMENT ON COLUMN COREQ_BOX.PROJECT.PLANCOST IS '예상 원가 절감비용';
COMMENT ON COLUMN COREQ_BOX.PROJECT.TOTALCOST IS '총 예상 비용';
COMMENT ON COLUMN COREQ_BOX.PROJECT.DESCRIPTION IS '비고';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CLIENTCOMPANY IS '고객사';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CLIENT IS '고객';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CLIENTPHONE IS '고객 연락처';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CLIENTPLANDATE IS '고객사 예상 완료일';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CLIENTPARTNO IS '고객 품번';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CLIENTPARTNAME IS '고객 품명';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CLIENTDESCRIPTION IS '내용';
COMMENT ON COLUMN COREQ_BOX.PROJECT.STATUS IS '상태';
COMMENT ON COLUMN COREQ_BOX.PROJECT.REFPROJECTCID IS 'WBS CID';
COMMENT ON COLUMN COREQ_BOX.PROJECT.TEMPLATENO IS 'PROJECT_TEMPLATE.NO';
COMMENT ON COLUMN COREQ_BOX.PROJECT.CLIENT_FILE IS '프로젝트 고객사 파일 ID';
COMMENT ON COLUMN COREQ_BOX.PROJECT.STATUSANALYSIS IS '현황분석';
COMMENT ON COLUMN COREQ_BOX.PROJECT.COMPETITIVESTRATEGY IS '경쟁전략';
COMMENT ON COLUMN COREQ_BOX.PROJECT.DEVELOPMENTSPECIFICATION IS '개발사양';


-- COREQ_BOX.PROJECT_FILE definition

CREATE TABLE "COREQ_BOX"."PROJECT_FILE" 
   (	"PROJECTCID" VARCHAR2(10), 
	"FILECID" VARCHAR2(43), 
	"TYPE" CHAR(1), 
	 CONSTRAINT "PK_PROJECTFILE" PRIMARY KEY ("PROJECTCID", "FILECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_PROJECTFILE" ON "COREQ_BOX"."PROJECT_FILE" ("PROJECTCID", "FILECID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON COLUMN COREQ_BOX.PROJECT_FILE.PROJECTCID IS '프로젝트 CID';
COMMENT ON COLUMN COREQ_BOX.PROJECT_FILE.FILECID IS '파일 CID';
COMMENT ON COLUMN COREQ_BOX.PROJECT_FILE."TYPE" IS '구분 0:프로젝트, 1:고객';


-- COREQ_BOX.PROJECT_MEMBER definition

CREATE TABLE "COREQ_BOX"."PROJECT_MEMBER" 
   (	"USERCID" VARCHAR2(20) NOT NULL ENABLE, 
	"PROJECTCID" VARCHAR2(10) NOT NULL ENABLE, 
	"PATICIPATE" VARCHAR2(5), 
	"PJRCID" VARCHAR2(10) DEFAULT 'PJR0000001' NOT NULL ENABLE, 
	 CONSTRAINT "PK_PROJECT_MEMBER" PRIMARY KEY ("PJRCID", "USERCID", "PROJECTCID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_PROJECT_MEMBER" ON "COREQ_BOX"."PROJECT_MEMBER" ("PJRCID", "USERCID", "PROJECTCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;


-- COREQ_BOX.USERS definition

CREATE TABLE "COREQ_BOX"."USERS" 
   (	"CID" VARCHAR2(20) NOT NULL ENABLE, 
	"NO" VARCHAR2(20) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(40) NOT NULL ENABLE, 
	"POSITION" VARCHAR2(20) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20), 
	"TEAMCID" VARCHAR2(30), 
	"COMPANYCID" VARCHAR2(10), 
	"TELEPHONENUMBER" VARCHAR2(20), 
	"MOBILENUMBER" VARCHAR2(20), 
	"OFFICENUMBER" VARCHAR2(20), 
	"ADMIN" CHAR(1) DEFAULT 0, 
	"DESCRIPTION" VARCHAR2(1000), 
	"ACCOUNT_ENABLED" CHAR(1) DEFAULT 1, 
	"ACCOUNT_EXPIRED" CHAR(1) DEFAULT 0, 
	"ACCOUNT_LOCKED" CHAR(1) DEFAULT 0, 
	"CREDENTIALS_EXPIRED" CHAR(1) DEFAULT 0, 
	"VERSION" NUMBER(38,0), 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	"CONTENT" CLOB, 
	"SIGN" BLOB, 
	"PHOTO" BLOB, 
	"SIGNCID" VARCHAR2(43), 
	"PHOTOCID" VARCHAR2(43), 
	"CLIENT" CHAR(1) DEFAULT '0', 
	"SEX" CHAR(1) DEFAULT '0', 
	"SHARING" VARCHAR2(20), 
	"FAXNUMBER1" VARCHAR2(20), 
	"HOMEPAGE1" VARCHAR2(255), 
	"ZIPCODE1" VARCHAR2(10), 
	"ADDRESS1" VARCHAR2(255), 
	"BUSINESS" VARCHAR2(255), 
	"CLIENTTEAM" VARCHAR2(255), 
	"CLIENTPOSITION" VARCHAR2(255), 
	"ORIGINATOR" VARCHAR2(20), 
	"DELETECLIENTFILE" CHAR(1) DEFAULT 0, 
	"REGID" VARCHAR2(200), 
	"SEQ_ZIPCODE" NUMBER, 
	"ABSENTEESET" CHAR(1) DEFAULT '0', 
	"ABSENTSTARTDATE" DATE, 
	"ABSENTENDDATE" DATE, 
	"ORIGINATOR_DURATION" VARCHAR2(2) DEFAULT 3, 
	"SEARCH_GRID_ROWS" VARCHAR2(20) DEFAULT 20, 
	 CONSTRAINT "PK_USERS" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE, 
	 CONSTRAINT "UK_NO_USERS" UNIQUE ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "COREQ_BOX_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("SIGN") STORE AS BASICFILE (
  TABLESPACE "COREQ_BOX_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PHOTO") STORE AS BASICFILE (
  TABLESPACE "COREQ_BOX_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "COREQ_BOX"."SYS_IL0000350731C00023$$" ON "COREQ_BOX"."USERS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "COREQ_BOX"."SYS_IL0000350731C00022$$" ON "COREQ_BOX"."USERS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "COREQ_BOX"."SYS_IL0000350731C00021$$" ON "COREQ_BOX"."USERS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "COREQ_BOX"."PK_USERS" ON "COREQ_BOX"."USERS" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;
  CREATE UNIQUE INDEX "COREQ_BOX"."UK_NO_USERS" ON "COREQ_BOX"."USERS" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.USERS IS '사용자 정보';
COMMENT ON COLUMN COREQ_BOX.USERS.CID IS '일련번호 : USR';
COMMENT ON COLUMN COREQ_BOX.USERS.COMPANYCID IS '회사';
COMMENT ON COLUMN COREQ_BOX.USERS.CREATEDATE IS '생성일';
COMMENT ON COLUMN COREQ_BOX.USERS.CONTENT IS '비고';
COMMENT ON COLUMN COREQ_BOX.USERS.SIGN IS '사인';
COMMENT ON COLUMN COREQ_BOX.USERS.PHOTO IS '사진';
COMMENT ON COLUMN COREQ_BOX.USERS.SIGNCID IS '사인파일 일련번호';
COMMENT ON COLUMN COREQ_BOX.USERS.PHOTOCID IS '사진파일 일련번호';
COMMENT ON COLUMN COREQ_BOX.USERS.REGID IS 'GCM 모바일 ID정보';
COMMENT ON COLUMN COREQ_BOX.USERS.ABSENTEESET IS '부재자 설정';
COMMENT ON COLUMN COREQ_BOX.USERS.ABSENTSTARTDATE IS '부재 시작일';
COMMENT ON COLUMN COREQ_BOX.USERS.ABSENTENDDATE IS '부재 종료일';
COMMENT ON COLUMN COREQ_BOX.USERS.ORIGINATOR_DURATION IS '검색조건에 생성일 DURATION설정';
COMMENT ON COLUMN COREQ_BOX.USERS.SEARCH_GRID_ROWS IS '검색결과 페이지별 항목수';


-- COREQ_BOX.USER_PROJECTROLE_RELATION definition

CREATE TABLE "COREQ_BOX"."USER_PROJECTROLE_RELATION" 
   (	"USERCID" VARCHAR2(20) NOT NULL ENABLE, 
	"ROLECID" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_USER_PROJECTROLE_RELATION" PRIMARY KEY ("USERCID", "ROLECID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_USER_PROJECTROLE_RELATION" ON "COREQ_BOX"."USER_PROJECTROLE_RELATION" ("USERCID", "ROLECID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;


-- COREQ_BOX.USER_TEAM_RELATION definition

CREATE TABLE "COREQ_BOX"."USER_TEAM_RELATION" 
   (	"TEAMCID" VARCHAR2(20) NOT NULL ENABLE, 
	"USERCID" VARCHAR2(20) NOT NULL ENABLE, 
	"MANAGER" CHAR(1) DEFAULT 0, 
	"DESCRIPTION" VARCHAR2(100), 
	"CREATEDATE" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "PK_USER_TEAM" PRIMARY KEY ("TEAMCID", "USERCID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_TBS" ;

CREATE UNIQUE INDEX "COREQ_BOX"."PK_USER_TEAM" ON "COREQ_BOX"."USER_TEAM_RELATION" ("TEAMCID", "USERCID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "COREQ_BOX_IDX" ;

COMMENT ON TABLE COREQ_BOX.USER_TEAM_RELATION IS '팀 사용자 연결 정보';
COMMENT ON COLUMN COREQ_BOX.USER_TEAM_RELATION.TEAMCID IS '팀 CID';
COMMENT ON COLUMN COREQ_BOX.USER_TEAM_RELATION.USERCID IS '사용자 CID';
COMMENT ON COLUMN COREQ_BOX.USER_TEAM_RELATION.MANAGER IS '팀장 여부';


-- COREQ_BOX.BOM foreign keys

ALTER TABLE "COREQ_BOX"."BOM" ADD CONSTRAINT "FK_CHILD_BOM" FOREIGN KEY ("CHILD")
	  REFERENCES "COREQ_BOX"."PART_MASTER" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."BOM" ADD CONSTRAINT "FK_PARENT_BOM" FOREIGN KEY ("PARENT")
	  REFERENCES "COREQ_BOX"."PART_MASTER" ("CID") ENABLE;


-- COREQ_BOX.CODE foreign keys

ALTER TABLE "COREQ_BOX"."CODE" ADD CONSTRAINT "FK_FORMAT_CODE" FOREIGN KEY ("FORMAT")
	  REFERENCES "COREQ_BOX"."FORMAT" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."CODE" ADD CONSTRAINT "FK_TYPE_CODE" FOREIGN KEY ("TYPECID")
	  REFERENCES "COREQ_BOX"."CODE_TYPE" ("CID") ENABLE;


-- COREQ_BOX.CODE_CATEGORY foreign keys

ALTER TABLE "COREQ_BOX"."CODE_CATEGORY" ADD CONSTRAINT "FK_CHILDCODE_CODECATEGORY" FOREIGN KEY ("CHILDCODE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."CODE_CATEGORY" ADD CONSTRAINT "FK_PARENTCODE_CODECATEGORY" FOREIGN KEY ("PARENTCODE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;


-- COREQ_BOX.MODEL_DETAIL foreign keys

ALTER TABLE "COREQ_BOX"."MODEL_DETAIL" ADD CONSTRAINT "FK_MASTER_MODELDETAIL" FOREIGN KEY ("MASTERCID")
	  REFERENCES "COREQ_BOX"."MODEL_MASTER" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_DETAIL" ADD CONSTRAINT "FK_ORIGINATOR_MODELDETAIL" FOREIGN KEY ("ORIGINATOR")
	  REFERENCES "COREQ_BOX"."USERS" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_DETAIL" ADD CONSTRAINT "FK_STATUS_MODELDETAIL" FOREIGN KEY ("STATUS")
	  REFERENCES "COREQ_BOX"."STATUS_CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_DETAIL" ADD CONSTRAINT "FK_MODELSRC_MODELDETAIL" FOREIGN KEY ("MODELSRC")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;


-- COREQ_BOX.MODEL_DETAIL_FILE foreign keys

ALTER TABLE "COREQ_BOX"."MODEL_DETAIL_FILE" ADD CONSTRAINT "FK_MODELSIZE_MODELDEATILFILE" FOREIGN KEY ("MODELSIZE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_DETAIL_FILE" ADD CONSTRAINT "FK_CHECKOUT_MODELDETAILFILE" FOREIGN KEY ("CHECKOUTUSER")
	  REFERENCES "COREQ_BOX"."USERS" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_DETAIL_FILE" ADD CONSTRAINT "FK_SOFTWARE_MODELDETAILFILE" FOREIGN KEY ("SOFTWARE")
	  REFERENCES "COREQ_BOX"."SOFTWARE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_DETAIL_FILE" ADD CONSTRAINT "FK_MODDET" FOREIGN KEY ("DETAILCID")
	  REFERENCES "COREQ_BOX"."MODEL_DETAIL" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_DETAIL_FILE" ADD CONSTRAINT "FK_CLASS_MODELDETAILFILE" FOREIGN KEY ("CLASSIFICATION")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_DETAIL_FILE" ADD CONSTRAINT "FK_TYPE_MODELDETAILFILE" FOREIGN KEY ("TYPE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;


-- COREQ_BOX.MODEL_FILE_RELATION foreign keys

ALTER TABLE "COREQ_BOX"."MODEL_FILE_RELATION" ADD CONSTRAINT "FK_MFR_MODDET" FOREIGN KEY ("MODELID")
	  REFERENCES "COREQ_BOX"."MODEL_DETAIL" ("CID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_FILE_RELATION" ADD CONSTRAINT "FK_MFR_MODFIL" FOREIGN KEY ("FILEID")
	  REFERENCES "COREQ_BOX"."MODEL_DETAIL_FILE" ("CID") ON DELETE CASCADE ENABLE;


-- COREQ_BOX.MODEL_MASTER foreign keys

ALTER TABLE "COREQ_BOX"."MODEL_MASTER" ADD CONSTRAINT "FK_STATUS_MODELMASTER" FOREIGN KEY ("STATUS")
	  REFERENCES "COREQ_BOX"."STATUS_CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."MODEL_MASTER" ADD CONSTRAINT "FK_PARTCID_MODELMASTER" FOREIGN KEY ("PARTCID")
	  REFERENCES "COREQ_BOX"."PART_DETAIL" ("CID") ENABLE;


-- COREQ_BOX.PART_DETAIL foreign keys

ALTER TABLE "COREQ_BOX"."PART_DETAIL" ADD CONSTRAINT "FK_SURFACE_PARTDETAIL" FOREIGN KEY ("SURFACE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_DETAIL" ADD CONSTRAINT "FK_MASTERCID_PARTDETAIL" FOREIGN KEY ("MASTERCID")
	  REFERENCES "COREQ_BOX"."PART_MASTER" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_DETAIL" ADD CONSTRAINT "FK_WEIGHT_UOM_PARTDETAIL" FOREIGN KEY ("WEIGHT_UOM")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_DETAIL" ADD CONSTRAINT "FK_MATTER_PARTDETAIL" FOREIGN KEY ("MATTER")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;


-- COREQ_BOX.PART_MASTER foreign keys

ALTER TABLE "COREQ_BOX"."PART_MASTER" ADD CONSTRAINT "FK_CLASSIFICATION_PARTMASTER" FOREIGN KEY ("CLASSIFICATION")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_MASTER" ADD CONSTRAINT "FK_UOM_PARTMASTER" FOREIGN KEY ("UOM")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_MASTER" ADD CONSTRAINT "FK_PRODUCTLINE_PARTMASTER" FOREIGN KEY ("PRODUCTLINE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_MASTER" ADD CONSTRAINT "FK_STATUS_PARTMASTER" FOREIGN KEY ("STATUS")
	  REFERENCES "COREQ_BOX"."STATUS_CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_MASTER" ADD CONSTRAINT "FK_TYPE_PARTMASTER" FOREIGN KEY ("TYPE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;


-- COREQ_BOX.PART_OBJECT_RELATION foreign keys

ALTER TABLE "COREQ_BOX"."PART_OBJECT_RELATION" ADD CONSTRAINT "FK_CLIENTCOMPAY_PARTOBJECTREL" FOREIGN KEY ("CLIENTCOMPAY")
	  REFERENCES "COREQ_BOX"."COMPANY" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_OBJECT_RELATION" ADD CONSTRAINT "FK_SUPPLYTYPE_PARTOBJECT" FOREIGN KEY ("SUPPLYTYPE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_OBJECT_RELATION" ADD CONSTRAINT "FK_CLIENT_PARTOBJECTREL" FOREIGN KEY ("CLIENT")
	  REFERENCES "COREQ_BOX"."USERS" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PART_OBJECT_RELATION" ADD CONSTRAINT "FK_PART_PARTOBJECTREL" FOREIGN KEY ("PARTID")
	  REFERENCES "COREQ_BOX"."PART_DETAIL" ("CID") ENABLE;


-- COREQ_BOX.PROJECT foreign keys

ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_GRADE_PROJECT" FOREIGN KEY ("GRADE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_TYPE_PROJECT" FOREIGN KEY ("TYPE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_PRODUCTLINE_PROJECT" FOREIGN KEY ("PRODUCTLINE")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_CLIENT_PROJECT" FOREIGN KEY ("CLIENT")
	  REFERENCES "COREQ_BOX"."USERS" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_MANAGER_PROJECT" FOREIGN KEY ("MANAGER")
	  REFERENCES "COREQ_BOX"."USERS" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_TYPICALPART_PROJECT" FOREIGN KEY ("TYPICALPART")
	  REFERENCES "COREQ_BOX"."PART_DETAIL" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_ORIGINATOR_PROJECT" FOREIGN KEY ("ORIGINATOR")
	  REFERENCES "COREQ_BOX"."USERS" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_CLIENTCOMPANY_PROJECT" FOREIGN KEY ("CLIENTCOMPANY")
	  REFERENCES "COREQ_BOX"."COMPANY" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT" ADD CONSTRAINT "FK_TEAM_PROJECT" FOREIGN KEY ("TEAM")
	  REFERENCES "COREQ_BOX"."TEAM" ("CID") ENABLE;


-- COREQ_BOX.PROJECT_FILE foreign keys

ALTER TABLE "COREQ_BOX"."PROJECT_FILE" ADD CONSTRAINT "FK_FILE_PROJECTFILE" FOREIGN KEY ("FILECID")
	  REFERENCES "COREQ_BOX"."ATTACHMENT_FILE" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."PROJECT_FILE" ADD CONSTRAINT "FK_PROJECT_PROJECTFILE" FOREIGN KEY ("PROJECTCID")
	  REFERENCES "COREQ_BOX"."PROJECT" ("CID") ENABLE;


-- COREQ_BOX.PROJECT_MEMBER foreign keys

ALTER TABLE "COREQ_BOX"."PROJECT_MEMBER" ADD CONSTRAINT "FK_PROJECT_MEMBER_PROJECTID_PRJCID" FOREIGN KEY ("PROJECTCID", "PJRCID")
	  REFERENCES "COREQ_BOX"."PROJECT_PROJECTROLE_REALTION" ("PROJECTCID", "PJRCID") ENABLE;


-- COREQ_BOX.USERS foreign keys

ALTER TABLE "COREQ_BOX"."USERS" ADD CONSTRAINT "FK_TEAMCID_USERS" FOREIGN KEY ("TEAMCID")
	  REFERENCES "COREQ_BOX"."TEAM" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."USERS" ADD CONSTRAINT "FK_POSITION_USERS" FOREIGN KEY ("POSITION")
	  REFERENCES "COREQ_BOX"."CODE" ("CID") ENABLE;


-- COREQ_BOX.USER_PROJECTROLE_RELATION foreign keys

ALTER TABLE "COREQ_BOX"."USER_PROJECTROLE_RELATION" ADD CONSTRAINT "FK_USER_PROJECTROLE_RELATION_USERCID" FOREIGN KEY ("USERCID")
	  REFERENCES "COREQ_BOX"."USERS" ("CID") ENABLE;


-- COREQ_BOX.USER_TEAM_RELATION foreign keys

ALTER TABLE "COREQ_BOX"."USER_TEAM_RELATION" ADD CONSTRAINT "FK_TEAMCID_USERTEAMRELATION" FOREIGN KEY ("TEAMCID")
	  REFERENCES "COREQ_BOX"."TEAM" ("CID") ENABLE;
  ALTER TABLE "COREQ_BOX"."USER_TEAM_RELATION" ADD CONSTRAINT "FK_USERCID_USERTEAMRELATION" FOREIGN KEY ("USERCID")
	  REFERENCES "COREQ_BOX"."USERS" ("CID") ENABLE;