INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000000', '대기(일정변경)');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000100', '작업중');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000200', '검토요청');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000300', '합의요청');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000400', '승인요청');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000500', '승인');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000600', '반려');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000700', '설계변경');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000800', '완료');
INSERT INTO COREQ_BOX.STATUS_CODE
(CID, DESCRIPTION)
VALUES('STA0000900', '미사용');
